// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// RemovePartiesFromProjectUsingDELETEReader is a Reader for the RemovePartiesFromProjectUsingDELETE structure.
type RemovePartiesFromProjectUsingDELETEReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemovePartiesFromProjectUsingDELETEReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRemovePartiesFromProjectUsingDELETEOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewRemovePartiesFromProjectUsingDELETENoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewRemovePartiesFromProjectUsingDELETEUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewRemovePartiesFromProjectUsingDELETEForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRemovePartiesFromProjectUsingDELETEOK creates a RemovePartiesFromProjectUsingDELETEOK with default headers values
func NewRemovePartiesFromProjectUsingDELETEOK() *RemovePartiesFromProjectUsingDELETEOK {
	return &RemovePartiesFromProjectUsingDELETEOK{}
}

/*RemovePartiesFromProjectUsingDELETEOK handles this case with default header values.

OK
*/
type RemovePartiesFromProjectUsingDELETEOK struct {
}

func (o *RemovePartiesFromProjectUsingDELETEOK) Error() string {
	return fmt.Sprintf("[DELETE /projects/{projectId}/parties][%d] removePartiesFromProjectUsingDELETEOK ", 200)
}

func (o *RemovePartiesFromProjectUsingDELETEOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRemovePartiesFromProjectUsingDELETENoContent creates a RemovePartiesFromProjectUsingDELETENoContent with default headers values
func NewRemovePartiesFromProjectUsingDELETENoContent() *RemovePartiesFromProjectUsingDELETENoContent {
	return &RemovePartiesFromProjectUsingDELETENoContent{}
}

/*RemovePartiesFromProjectUsingDELETENoContent handles this case with default header values.

No Content
*/
type RemovePartiesFromProjectUsingDELETENoContent struct {
}

func (o *RemovePartiesFromProjectUsingDELETENoContent) Error() string {
	return fmt.Sprintf("[DELETE /projects/{projectId}/parties][%d] removePartiesFromProjectUsingDELETENoContent ", 204)
}

func (o *RemovePartiesFromProjectUsingDELETENoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRemovePartiesFromProjectUsingDELETEUnauthorized creates a RemovePartiesFromProjectUsingDELETEUnauthorized with default headers values
func NewRemovePartiesFromProjectUsingDELETEUnauthorized() *RemovePartiesFromProjectUsingDELETEUnauthorized {
	return &RemovePartiesFromProjectUsingDELETEUnauthorized{}
}

/*RemovePartiesFromProjectUsingDELETEUnauthorized handles this case with default header values.

Unauthorized
*/
type RemovePartiesFromProjectUsingDELETEUnauthorized struct {
}

func (o *RemovePartiesFromProjectUsingDELETEUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /projects/{projectId}/parties][%d] removePartiesFromProjectUsingDELETEUnauthorized ", 401)
}

func (o *RemovePartiesFromProjectUsingDELETEUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRemovePartiesFromProjectUsingDELETEForbidden creates a RemovePartiesFromProjectUsingDELETEForbidden with default headers values
func NewRemovePartiesFromProjectUsingDELETEForbidden() *RemovePartiesFromProjectUsingDELETEForbidden {
	return &RemovePartiesFromProjectUsingDELETEForbidden{}
}

/*RemovePartiesFromProjectUsingDELETEForbidden handles this case with default header values.

Forbidden
*/
type RemovePartiesFromProjectUsingDELETEForbidden struct {
}

func (o *RemovePartiesFromProjectUsingDELETEForbidden) Error() string {
	return fmt.Sprintf("[DELETE /projects/{projectId}/parties][%d] removePartiesFromProjectUsingDELETEForbidden ", 403)
}

func (o *RemovePartiesFromProjectUsingDELETEForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
