/*
 * ADMINISTRATION
 *
 * Retrieves, syncs, and deletes administration data
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RegisteredPluginServerDto struct {
	Id int64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	PluginServerAddress string `json:"pluginServerAddress,omitempty"`
	PluginServerPort int32 `json:"pluginServerPort,omitempty"`
	PluginServerSchema string `json:"pluginServerSchema,omitempty"`
}
