/*
 * ADMINISTRATION
 *
 * Retrieves, syncs, and deletes administration data
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PaymentPlanDto struct {
	BillingPortalURL string `json:"billingPortalURL,omitempty"`
	CreationDate int64 `json:"creationDate,omitempty"`
	CreatorEmail string `json:"creatorEmail,omitempty"`
	CreatorFirstName string `json:"creatorFirstName,omitempty"`
	CreatorLastName string `json:"creatorLastName,omitempty"`
	Id int64 `json:"id,omitempty"`
	PaymentPlanId string `json:"paymentPlanId,omitempty"`
	PaymentPlanName string `json:"paymentPlanName,omitempty"`
	SubscriptionId string `json:"subscriptionId,omitempty"`
}
