/*
 * ADMINISTRATION
 *
 * Retrieves, syncs, and deletes administration data
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PortfolioLicensingAgreementDto struct {
	CompanyEmailDomain string `json:"companyEmailDomain,omitempty"`
	ConcurrentRunningReleases int32 `json:"concurrentRunningReleases,omitempty"`
	CoveredByBroadcomSubscriptionPLA bool `json:"coveredByBroadcomSubscriptionPLA,omitempty"`
	DepartmentChargeIdentifier string `json:"departmentChargeIdentifier,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	EnterpriseSiteId int64 `json:"enterpriseSiteId,omitempty"`
	Id int64 `json:"id,omitempty"`
	InstanceId string `json:"instanceId,omitempty"`
	LastCollectionDate int64 `json:"lastCollectionDate,omitempty"`
	LastCollectionStatus string `json:"lastCollectionStatus,omitempty"`
	Name string `json:"name,omitempty"`
	ProductVersionName string `json:"productVersionName,omitempty"`
	ProxyPassword string `json:"proxyPassword,omitempty"`
	ProxyURL string `json:"proxyURL,omitempty"`
	ProxyUsername string `json:"proxyUsername,omitempty"`
	UseProxy bool `json:"useProxy,omitempty"`
}
