/*
 * ADMINISTRATION
 *
 * Retrieves, syncs, and deletes administration data
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DynamicValuesInputDto struct {
	EndpointId int64 `json:"endpointId,omitempty"`
	PluginServiceContext []KeyValueDto `json:"pluginServiceContext,omitempty"`
}
