/*
 * ADMINISTRATION
 *
 * Retrieves, syncs, and deletes administration data
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ListHolderDtoEmailNotificationTemplateDto struct {
	Data []EmailNotificationTemplateDto `json:"data,omitempty"`
}
