/*
 * REPORTING
 *
 * Retrieves, updates, and deletes report and widget information
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type StatusReasonCountersDto struct {
	FailureDeployment int64 `json:"failureDeployment,omitempty"`
	FailureEnvironment int64 `json:"failureEnvironment,omitempty"`
	FailureFunctional int64 `json:"failureFunctional,omitempty"`
	FailureGeneral int64 `json:"failureGeneral,omitempty"`
	FailurePerformance int64 `json:"failurePerformance,omitempty"`
	NotInUse int64 `json:"notInUse,omitempty"`
	Success int64 `json:"success,omitempty"`
}
