/*
 * REPORTING
 *
 * Retrieves, updates, and deletes report and widget information
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type FilterDto struct {
	Alias string `json:"alias,omitempty"`
	And bool `json:"and,omitempty"`
	NamedParameter string `json:"namedParameter,omitempty"`
	Operator string `json:"operator,omitempty"`
	Value *interface{} `json:"value,omitempty"`
}
