// Code generated by go-swagger; DO NOT EDIT.

package test_suite

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// AddTagsAndIsFavoriteToTestSuitesUsingPATCHReader is a Reader for the AddTagsAndIsFavoriteToTestSuitesUsingPATCH structure.
type AddTagsAndIsFavoriteToTestSuitesUsingPATCHReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddTagsAndIsFavoriteToTestSuitesUsingPATCHReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddTagsAndIsFavoriteToTestSuitesUsingPATCHOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewAddTagsAndIsFavoriteToTestSuitesUsingPATCHNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewAddTagsAndIsFavoriteToTestSuitesUsingPATCHUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewAddTagsAndIsFavoriteToTestSuitesUsingPATCHForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddTagsAndIsFavoriteToTestSuitesUsingPATCHOK creates a AddTagsAndIsFavoriteToTestSuitesUsingPATCHOK with default headers values
func NewAddTagsAndIsFavoriteToTestSuitesUsingPATCHOK() *AddTagsAndIsFavoriteToTestSuitesUsingPATCHOK {
	return &AddTagsAndIsFavoriteToTestSuitesUsingPATCHOK{}
}

/*AddTagsAndIsFavoriteToTestSuitesUsingPATCHOK handles this case with default header values.

OK
*/
type AddTagsAndIsFavoriteToTestSuitesUsingPATCHOK struct {
}

func (o *AddTagsAndIsFavoriteToTestSuitesUsingPATCHOK) Error() string {
	return fmt.Sprintf("[PATCH /applications/{applicationId}/application-versions/{applicationVersionId}/test-suites][%d] addTagsAndIsFavoriteToTestSuitesUsingPATCHOK ", 200)
}

func (o *AddTagsAndIsFavoriteToTestSuitesUsingPATCHOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddTagsAndIsFavoriteToTestSuitesUsingPATCHNoContent creates a AddTagsAndIsFavoriteToTestSuitesUsingPATCHNoContent with default headers values
func NewAddTagsAndIsFavoriteToTestSuitesUsingPATCHNoContent() *AddTagsAndIsFavoriteToTestSuitesUsingPATCHNoContent {
	return &AddTagsAndIsFavoriteToTestSuitesUsingPATCHNoContent{}
}

/*AddTagsAndIsFavoriteToTestSuitesUsingPATCHNoContent handles this case with default header values.

No Content
*/
type AddTagsAndIsFavoriteToTestSuitesUsingPATCHNoContent struct {
}

func (o *AddTagsAndIsFavoriteToTestSuitesUsingPATCHNoContent) Error() string {
	return fmt.Sprintf("[PATCH /applications/{applicationId}/application-versions/{applicationVersionId}/test-suites][%d] addTagsAndIsFavoriteToTestSuitesUsingPATCHNoContent ", 204)
}

func (o *AddTagsAndIsFavoriteToTestSuitesUsingPATCHNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddTagsAndIsFavoriteToTestSuitesUsingPATCHUnauthorized creates a AddTagsAndIsFavoriteToTestSuitesUsingPATCHUnauthorized with default headers values
func NewAddTagsAndIsFavoriteToTestSuitesUsingPATCHUnauthorized() *AddTagsAndIsFavoriteToTestSuitesUsingPATCHUnauthorized {
	return &AddTagsAndIsFavoriteToTestSuitesUsingPATCHUnauthorized{}
}

/*AddTagsAndIsFavoriteToTestSuitesUsingPATCHUnauthorized handles this case with default header values.

Unauthorized
*/
type AddTagsAndIsFavoriteToTestSuitesUsingPATCHUnauthorized struct {
}

func (o *AddTagsAndIsFavoriteToTestSuitesUsingPATCHUnauthorized) Error() string {
	return fmt.Sprintf("[PATCH /applications/{applicationId}/application-versions/{applicationVersionId}/test-suites][%d] addTagsAndIsFavoriteToTestSuitesUsingPATCHUnauthorized ", 401)
}

func (o *AddTagsAndIsFavoriteToTestSuitesUsingPATCHUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddTagsAndIsFavoriteToTestSuitesUsingPATCHForbidden creates a AddTagsAndIsFavoriteToTestSuitesUsingPATCHForbidden with default headers values
func NewAddTagsAndIsFavoriteToTestSuitesUsingPATCHForbidden() *AddTagsAndIsFavoriteToTestSuitesUsingPATCHForbidden {
	return &AddTagsAndIsFavoriteToTestSuitesUsingPATCHForbidden{}
}

/*AddTagsAndIsFavoriteToTestSuitesUsingPATCHForbidden handles this case with default header values.

Forbidden
*/
type AddTagsAndIsFavoriteToTestSuitesUsingPATCHForbidden struct {
}

func (o *AddTagsAndIsFavoriteToTestSuitesUsingPATCHForbidden) Error() string {
	return fmt.Sprintf("[PATCH /applications/{applicationId}/application-versions/{applicationVersionId}/test-suites][%d] addTagsAndIsFavoriteToTestSuitesUsingPATCHForbidden ", 403)
}

func (o *AddTagsAndIsFavoriteToTestSuitesUsingPATCHForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
