/*
 * EXECUTION
 *
 * Retrieves and changes execution data
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ReleaseTokenValueDto struct {
	Id int64 `json:"id,omitempty"`
	ReleaseManifest *NamedIdentifiableDto `json:"releaseManifest,omitempty"`
	ReleaseToken *NamedIdentifiableDto `json:"releaseToken,omitempty"`
	TokenDisplayName string `json:"tokenDisplayName,omitempty"`
	Value string `json:"value,omitempty"`
}
