/*
 * EXECUTION
 *
 * Retrieves and changes execution data
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CommitFilesDto struct {
	CommitId string `json:"commitId,omitempty"`
	Files []CommitChangeFileDto `json:"files,omitempty"`
}
