// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/e88z4/go_cdd/administration/models"
)

// NewUpdateRoleUsingPUTParams creates a new UpdateRoleUsingPUTParams object
// with the default values initialized.
func NewUpdateRoleUsingPUTParams() *UpdateRoleUsingPUTParams {
	var ()
	return &UpdateRoleUsingPUTParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRoleUsingPUTParamsWithTimeout creates a new UpdateRoleUsingPUTParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateRoleUsingPUTParamsWithTimeout(timeout time.Duration) *UpdateRoleUsingPUTParams {
	var ()
	return &UpdateRoleUsingPUTParams{

		timeout: timeout,
	}
}

// NewUpdateRoleUsingPUTParamsWithContext creates a new UpdateRoleUsingPUTParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateRoleUsingPUTParamsWithContext(ctx context.Context) *UpdateRoleUsingPUTParams {
	var ()
	return &UpdateRoleUsingPUTParams{

		Context: ctx,
	}
}

// NewUpdateRoleUsingPUTParamsWithHTTPClient creates a new UpdateRoleUsingPUTParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateRoleUsingPUTParamsWithHTTPClient(client *http.Client) *UpdateRoleUsingPUTParams {
	var ()
	return &UpdateRoleUsingPUTParams{
		HTTPClient: client,
	}
}

/*UpdateRoleUsingPUTParams contains all the parameters to send to the API endpoint
for the update role using p u t operation typically these are written to a http.Request
*/
type UpdateRoleUsingPUTParams struct {

	/*RoleDto
	  roleDto

	*/
	RoleDto *models.RoleDto
	/*RoleID
	  roleId

	*/
	RoleID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update role using p u t params
func (o *UpdateRoleUsingPUTParams) WithTimeout(timeout time.Duration) *UpdateRoleUsingPUTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update role using p u t params
func (o *UpdateRoleUsingPUTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update role using p u t params
func (o *UpdateRoleUsingPUTParams) WithContext(ctx context.Context) *UpdateRoleUsingPUTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update role using p u t params
func (o *UpdateRoleUsingPUTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update role using p u t params
func (o *UpdateRoleUsingPUTParams) WithHTTPClient(client *http.Client) *UpdateRoleUsingPUTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update role using p u t params
func (o *UpdateRoleUsingPUTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRoleDto adds the roleDto to the update role using p u t params
func (o *UpdateRoleUsingPUTParams) WithRoleDto(roleDto *models.RoleDto) *UpdateRoleUsingPUTParams {
	o.SetRoleDto(roleDto)
	return o
}

// SetRoleDto adds the roleDto to the update role using p u t params
func (o *UpdateRoleUsingPUTParams) SetRoleDto(roleDto *models.RoleDto) {
	o.RoleDto = roleDto
}

// WithRoleID adds the roleID to the update role using p u t params
func (o *UpdateRoleUsingPUTParams) WithRoleID(roleID int64) *UpdateRoleUsingPUTParams {
	o.SetRoleID(roleID)
	return o
}

// SetRoleID adds the roleId to the update role using p u t params
func (o *UpdateRoleUsingPUTParams) SetRoleID(roleID int64) {
	o.RoleID = roleID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRoleUsingPUTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.RoleDto != nil {
		if err := r.SetBodyParam(o.RoleDto); err != nil {
			return err
		}
	}

	// path param roleId
	if err := r.SetPathParam("roleId", swag.FormatInt64(o.RoleID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
