// Code generated by go-swagger; DO NOT EDIT.

package dsl

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewExportTestSourcesUsingGETParams creates a new ExportTestSourcesUsingGETParams object
// with the default values initialized.
func NewExportTestSourcesUsingGETParams() *ExportTestSourcesUsingGETParams {
	var ()
	return &ExportTestSourcesUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewExportTestSourcesUsingGETParamsWithTimeout creates a new ExportTestSourcesUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewExportTestSourcesUsingGETParamsWithTimeout(timeout time.Duration) *ExportTestSourcesUsingGETParams {
	var ()
	return &ExportTestSourcesUsingGETParams{

		timeout: timeout,
	}
}

// NewExportTestSourcesUsingGETParamsWithContext creates a new ExportTestSourcesUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewExportTestSourcesUsingGETParamsWithContext(ctx context.Context) *ExportTestSourcesUsingGETParams {
	var ()
	return &ExportTestSourcesUsingGETParams{

		Context: ctx,
	}
}

// NewExportTestSourcesUsingGETParamsWithHTTPClient creates a new ExportTestSourcesUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewExportTestSourcesUsingGETParamsWithHTTPClient(client *http.Client) *ExportTestSourcesUsingGETParams {
	var ()
	return &ExportTestSourcesUsingGETParams{
		HTTPClient: client,
	}
}

/*ExportTestSourcesUsingGETParams contains all the parameters to send to the API endpoint
for the export test sources using g e t operation typically these are written to a http.Request
*/
type ExportTestSourcesUsingGETParams struct {

	/*ApplicationVersionID
	  applicationVersionId

	*/
	ApplicationVersionID int64
	/*DispositionType
	  dispositionTypeDto

	*/
	DispositionType *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the export test sources using g e t params
func (o *ExportTestSourcesUsingGETParams) WithTimeout(timeout time.Duration) *ExportTestSourcesUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the export test sources using g e t params
func (o *ExportTestSourcesUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the export test sources using g e t params
func (o *ExportTestSourcesUsingGETParams) WithContext(ctx context.Context) *ExportTestSourcesUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the export test sources using g e t params
func (o *ExportTestSourcesUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the export test sources using g e t params
func (o *ExportTestSourcesUsingGETParams) WithHTTPClient(client *http.Client) *ExportTestSourcesUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the export test sources using g e t params
func (o *ExportTestSourcesUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApplicationVersionID adds the applicationVersionID to the export test sources using g e t params
func (o *ExportTestSourcesUsingGETParams) WithApplicationVersionID(applicationVersionID int64) *ExportTestSourcesUsingGETParams {
	o.SetApplicationVersionID(applicationVersionID)
	return o
}

// SetApplicationVersionID adds the applicationVersionId to the export test sources using g e t params
func (o *ExportTestSourcesUsingGETParams) SetApplicationVersionID(applicationVersionID int64) {
	o.ApplicationVersionID = applicationVersionID
}

// WithDispositionType adds the dispositionType to the export test sources using g e t params
func (o *ExportTestSourcesUsingGETParams) WithDispositionType(dispositionType *string) *ExportTestSourcesUsingGETParams {
	o.SetDispositionType(dispositionType)
	return o
}

// SetDispositionType adds the dispositionType to the export test sources using g e t params
func (o *ExportTestSourcesUsingGETParams) SetDispositionType(dispositionType *string) {
	o.DispositionType = dispositionType
}

// WriteToRequest writes these params to a swagger request
func (o *ExportTestSourcesUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param applicationVersionId
	if err := r.SetPathParam("applicationVersionId", swag.FormatInt64(o.ApplicationVersionID)); err != nil {
		return err
	}

	if o.DispositionType != nil {

		// query param disposition_type
		var qrDispositionType string
		if o.DispositionType != nil {
			qrDispositionType = *o.DispositionType
		}
		qDispositionType := qrDispositionType
		if qDispositionType != "" {
			if err := r.SetQueryParam("disposition_type", qDispositionType); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
