// Code generated by go-swagger; DO NOT EDIT.

package execution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAllPhaseTasksExecutionUsingGETParams creates a new GetAllPhaseTasksExecutionUsingGETParams object
// with the default values initialized.
func NewGetAllPhaseTasksExecutionUsingGETParams() *GetAllPhaseTasksExecutionUsingGETParams {
	var ()
	return &GetAllPhaseTasksExecutionUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllPhaseTasksExecutionUsingGETParamsWithTimeout creates a new GetAllPhaseTasksExecutionUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllPhaseTasksExecutionUsingGETParamsWithTimeout(timeout time.Duration) *GetAllPhaseTasksExecutionUsingGETParams {
	var ()
	return &GetAllPhaseTasksExecutionUsingGETParams{

		timeout: timeout,
	}
}

// NewGetAllPhaseTasksExecutionUsingGETParamsWithContext creates a new GetAllPhaseTasksExecutionUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllPhaseTasksExecutionUsingGETParamsWithContext(ctx context.Context) *GetAllPhaseTasksExecutionUsingGETParams {
	var ()
	return &GetAllPhaseTasksExecutionUsingGETParams{

		Context: ctx,
	}
}

// NewGetAllPhaseTasksExecutionUsingGETParamsWithHTTPClient creates a new GetAllPhaseTasksExecutionUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllPhaseTasksExecutionUsingGETParamsWithHTTPClient(client *http.Client) *GetAllPhaseTasksExecutionUsingGETParams {
	var ()
	return &GetAllPhaseTasksExecutionUsingGETParams{
		HTTPClient: client,
	}
}

/*GetAllPhaseTasksExecutionUsingGETParams contains all the parameters to send to the API endpoint
for the get all phase tasks execution using g e t operation typically these are written to a http.Request
*/
type GetAllPhaseTasksExecutionUsingGETParams struct {

	/*PhaseID
	  phaseId

	*/
	PhaseID int64
	/*ReleaseID
	  releaseId

	*/
	ReleaseID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all phase tasks execution using g e t params
func (o *GetAllPhaseTasksExecutionUsingGETParams) WithTimeout(timeout time.Duration) *GetAllPhaseTasksExecutionUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all phase tasks execution using g e t params
func (o *GetAllPhaseTasksExecutionUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all phase tasks execution using g e t params
func (o *GetAllPhaseTasksExecutionUsingGETParams) WithContext(ctx context.Context) *GetAllPhaseTasksExecutionUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all phase tasks execution using g e t params
func (o *GetAllPhaseTasksExecutionUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all phase tasks execution using g e t params
func (o *GetAllPhaseTasksExecutionUsingGETParams) WithHTTPClient(client *http.Client) *GetAllPhaseTasksExecutionUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all phase tasks execution using g e t params
func (o *GetAllPhaseTasksExecutionUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPhaseID adds the phaseID to the get all phase tasks execution using g e t params
func (o *GetAllPhaseTasksExecutionUsingGETParams) WithPhaseID(phaseID int64) *GetAllPhaseTasksExecutionUsingGETParams {
	o.SetPhaseID(phaseID)
	return o
}

// SetPhaseID adds the phaseId to the get all phase tasks execution using g e t params
func (o *GetAllPhaseTasksExecutionUsingGETParams) SetPhaseID(phaseID int64) {
	o.PhaseID = phaseID
}

// WithReleaseID adds the releaseID to the get all phase tasks execution using g e t params
func (o *GetAllPhaseTasksExecutionUsingGETParams) WithReleaseID(releaseID int64) *GetAllPhaseTasksExecutionUsingGETParams {
	o.SetReleaseID(releaseID)
	return o
}

// SetReleaseID adds the releaseId to the get all phase tasks execution using g e t params
func (o *GetAllPhaseTasksExecutionUsingGETParams) SetReleaseID(releaseID int64) {
	o.ReleaseID = releaseID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllPhaseTasksExecutionUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param phaseId
	if err := r.SetPathParam("phaseId", swag.FormatInt64(o.PhaseID)); err != nil {
		return err
	}

	// path param releaseId
	if err := r.SetPathParam("releaseId", swag.FormatInt64(o.ReleaseID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
