// Code generated by go-swagger; DO NOT EDIT.

package execution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetReleaseExecutionUsingGETParams creates a new GetReleaseExecutionUsingGETParams object
// with the default values initialized.
func NewGetReleaseExecutionUsingGETParams() *GetReleaseExecutionUsingGETParams {
	var ()
	return &GetReleaseExecutionUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetReleaseExecutionUsingGETParamsWithTimeout creates a new GetReleaseExecutionUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetReleaseExecutionUsingGETParamsWithTimeout(timeout time.Duration) *GetReleaseExecutionUsingGETParams {
	var ()
	return &GetReleaseExecutionUsingGETParams{

		timeout: timeout,
	}
}

// NewGetReleaseExecutionUsingGETParamsWithContext creates a new GetReleaseExecutionUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetReleaseExecutionUsingGETParamsWithContext(ctx context.Context) *GetReleaseExecutionUsingGETParams {
	var ()
	return &GetReleaseExecutionUsingGETParams{

		Context: ctx,
	}
}

// NewGetReleaseExecutionUsingGETParamsWithHTTPClient creates a new GetReleaseExecutionUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetReleaseExecutionUsingGETParamsWithHTTPClient(client *http.Client) *GetReleaseExecutionUsingGETParams {
	var ()
	return &GetReleaseExecutionUsingGETParams{
		HTTPClient: client,
	}
}

/*GetReleaseExecutionUsingGETParams contains all the parameters to send to the API endpoint
for the get release execution using g e t operation typically these are written to a http.Request
*/
type GetReleaseExecutionUsingGETParams struct {

	/*ReleaseID
	  releaseId

	*/
	ReleaseID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get release execution using g e t params
func (o *GetReleaseExecutionUsingGETParams) WithTimeout(timeout time.Duration) *GetReleaseExecutionUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get release execution using g e t params
func (o *GetReleaseExecutionUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get release execution using g e t params
func (o *GetReleaseExecutionUsingGETParams) WithContext(ctx context.Context) *GetReleaseExecutionUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get release execution using g e t params
func (o *GetReleaseExecutionUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get release execution using g e t params
func (o *GetReleaseExecutionUsingGETParams) WithHTTPClient(client *http.Client) *GetReleaseExecutionUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get release execution using g e t params
func (o *GetReleaseExecutionUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReleaseID adds the releaseID to the get release execution using g e t params
func (o *GetReleaseExecutionUsingGETParams) WithReleaseID(releaseID int64) *GetReleaseExecutionUsingGETParams {
	o.SetReleaseID(releaseID)
	return o
}

// SetReleaseID adds the releaseId to the get release execution using g e t params
func (o *GetReleaseExecutionUsingGETParams) SetReleaseID(releaseID int64) {
	o.ReleaseID = releaseID
}

// WriteToRequest writes these params to a swagger request
func (o *GetReleaseExecutionUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param releaseId
	if err := r.SetPathParam("releaseId", swag.FormatInt64(o.ReleaseID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
