/*
 * DESIGN
 *
 * Retrieves, updates, and deletes design data
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CommitChangeFileDto struct {
	ChangeId string `json:"changeId,omitempty"`
	CommitId string `json:"commitId,omitempty"`
	Filename string `json:"filename,omitempty"`
	Id string `json:"id,omitempty"`
	IsCovered bool `json:"isCovered,omitempty"`
	IsExcluded bool `json:"isExcluded,omitempty"`
	TestSuites []TestSuiteDto `json:"testSuites,omitempty"`
}
