/*
 * DESIGN
 *
 * Retrieves, updates, and deletes design data
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ListHolderDtoNamedIdentifiableDto struct {
	Data []NamedIdentifiableDto `json:"data,omitempty"`
}
