// Code generated by go-swagger; DO NOT EDIT.

package email_notification_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetEmailNotificationServerUsingGETParams creates a new GetEmailNotificationServerUsingGETParams object
// with the default values initialized.
func NewGetEmailNotificationServerUsingGETParams() *GetEmailNotificationServerUsingGETParams {
	var ()
	return &GetEmailNotificationServerUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetEmailNotificationServerUsingGETParamsWithTimeout creates a new GetEmailNotificationServerUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetEmailNotificationServerUsingGETParamsWithTimeout(timeout time.Duration) *GetEmailNotificationServerUsingGETParams {
	var ()
	return &GetEmailNotificationServerUsingGETParams{

		timeout: timeout,
	}
}

// NewGetEmailNotificationServerUsingGETParamsWithContext creates a new GetEmailNotificationServerUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetEmailNotificationServerUsingGETParamsWithContext(ctx context.Context) *GetEmailNotificationServerUsingGETParams {
	var ()
	return &GetEmailNotificationServerUsingGETParams{

		Context: ctx,
	}
}

// NewGetEmailNotificationServerUsingGETParamsWithHTTPClient creates a new GetEmailNotificationServerUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetEmailNotificationServerUsingGETParamsWithHTTPClient(client *http.Client) *GetEmailNotificationServerUsingGETParams {
	var ()
	return &GetEmailNotificationServerUsingGETParams{
		HTTPClient: client,
	}
}

/*GetEmailNotificationServerUsingGETParams contains all the parameters to send to the API endpoint
for the get email notification server using g e t operation typically these are written to a http.Request
*/
type GetEmailNotificationServerUsingGETParams struct {

	/*EmailNotificationServerID
	  emailNotificationServerId

	*/
	EmailNotificationServerID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get email notification server using g e t params
func (o *GetEmailNotificationServerUsingGETParams) WithTimeout(timeout time.Duration) *GetEmailNotificationServerUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get email notification server using g e t params
func (o *GetEmailNotificationServerUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get email notification server using g e t params
func (o *GetEmailNotificationServerUsingGETParams) WithContext(ctx context.Context) *GetEmailNotificationServerUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get email notification server using g e t params
func (o *GetEmailNotificationServerUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get email notification server using g e t params
func (o *GetEmailNotificationServerUsingGETParams) WithHTTPClient(client *http.Client) *GetEmailNotificationServerUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get email notification server using g e t params
func (o *GetEmailNotificationServerUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmailNotificationServerID adds the emailNotificationServerID to the get email notification server using g e t params
func (o *GetEmailNotificationServerUsingGETParams) WithEmailNotificationServerID(emailNotificationServerID int64) *GetEmailNotificationServerUsingGETParams {
	o.SetEmailNotificationServerID(emailNotificationServerID)
	return o
}

// SetEmailNotificationServerID adds the emailNotificationServerId to the get email notification server using g e t params
func (o *GetEmailNotificationServerUsingGETParams) SetEmailNotificationServerID(emailNotificationServerID int64) {
	o.EmailNotificationServerID = emailNotificationServerID
}

// WriteToRequest writes these params to a swagger request
func (o *GetEmailNotificationServerUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param emailNotificationServerId
	if err := r.SetPathParam("emailNotificationServerId", swag.FormatInt64(o.EmailNotificationServerID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
