// Code generated by go-swagger; DO NOT EDIT.

package plugin_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/e88z4/go_cdd/administration/models"
)

// GetPluginServiceTemplateUsingGETReader is a Reader for the GetPluginServiceTemplateUsingGET structure.
type GetPluginServiceTemplateUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPluginServiceTemplateUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPluginServiceTemplateUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetPluginServiceTemplateUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetPluginServiceTemplateUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetPluginServiceTemplateUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPluginServiceTemplateUsingGETOK creates a GetPluginServiceTemplateUsingGETOK with default headers values
func NewGetPluginServiceTemplateUsingGETOK() *GetPluginServiceTemplateUsingGETOK {
	return &GetPluginServiceTemplateUsingGETOK{}
}

/*GetPluginServiceTemplateUsingGETOK handles this case with default header values.

OK
*/
type GetPluginServiceTemplateUsingGETOK struct {
	Payload *models.PluginServiceTemplateDto
}

func (o *GetPluginServiceTemplateUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /plugin-service-templates/{pluginServiceTemplateId}][%d] getPluginServiceTemplateUsingGETOK  %+v", 200, o.Payload)
}

func (o *GetPluginServiceTemplateUsingGETOK) GetPayload() *models.PluginServiceTemplateDto {
	return o.Payload
}

func (o *GetPluginServiceTemplateUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PluginServiceTemplateDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPluginServiceTemplateUsingGETUnauthorized creates a GetPluginServiceTemplateUsingGETUnauthorized with default headers values
func NewGetPluginServiceTemplateUsingGETUnauthorized() *GetPluginServiceTemplateUsingGETUnauthorized {
	return &GetPluginServiceTemplateUsingGETUnauthorized{}
}

/*GetPluginServiceTemplateUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type GetPluginServiceTemplateUsingGETUnauthorized struct {
}

func (o *GetPluginServiceTemplateUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /plugin-service-templates/{pluginServiceTemplateId}][%d] getPluginServiceTemplateUsingGETUnauthorized ", 401)
}

func (o *GetPluginServiceTemplateUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPluginServiceTemplateUsingGETForbidden creates a GetPluginServiceTemplateUsingGETForbidden with default headers values
func NewGetPluginServiceTemplateUsingGETForbidden() *GetPluginServiceTemplateUsingGETForbidden {
	return &GetPluginServiceTemplateUsingGETForbidden{}
}

/*GetPluginServiceTemplateUsingGETForbidden handles this case with default header values.

Forbidden
*/
type GetPluginServiceTemplateUsingGETForbidden struct {
}

func (o *GetPluginServiceTemplateUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /plugin-service-templates/{pluginServiceTemplateId}][%d] getPluginServiceTemplateUsingGETForbidden ", 403)
}

func (o *GetPluginServiceTemplateUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPluginServiceTemplateUsingGETNotFound creates a GetPluginServiceTemplateUsingGETNotFound with default headers values
func NewGetPluginServiceTemplateUsingGETNotFound() *GetPluginServiceTemplateUsingGETNotFound {
	return &GetPluginServiceTemplateUsingGETNotFound{}
}

/*GetPluginServiceTemplateUsingGETNotFound handles this case with default header values.

Not Found
*/
type GetPluginServiceTemplateUsingGETNotFound struct {
}

func (o *GetPluginServiceTemplateUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /plugin-service-templates/{pluginServiceTemplateId}][%d] getPluginServiceTemplateUsingGETNotFound ", 404)
}

func (o *GetPluginServiceTemplateUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
