// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIAccessTokenDto Api access token dto
// swagger:model ApiAccessTokenDto
type APIAccessTokenDto struct {

	// api access token
	APIAccessToken string `json:"apiAccessToken,omitempty"`

	// creation date
	CreationDate int64 `json:"creationDate,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// tenant Id
	TenantID string `json:"tenantId,omitempty"`

	// tenant name
	TenantName string `json:"tenantName,omitempty"`
}

// Validate validates this Api access token dto
func (m *APIAccessTokenDto) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIAccessTokenDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIAccessTokenDto) UnmarshalBinary(b []byte) error {
	var res APIAccessTokenDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
