// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HelpAboutDto help about dto
// swagger:model HelpAboutDto
type HelpAboutDto struct {

	// enabled
	Enabled bool `json:"enabled,omitempty"`
}

// Validate validates this help about dto
func (m *HelpAboutDto) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HelpAboutDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HelpAboutDto) UnmarshalBinary(b []byte) error {
	var res HelpAboutDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
