// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// POPPermissionDto p o p permission dto
// swagger:model POPPermissionDto
type POPPermissionDto struct {

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// is plugin proxy enabled
	IsPluginProxyEnabled bool `json:"isPluginProxyEnabled,omitempty"`
}

// Validate validates this p o p permission dto
func (m *POPPermissionDto) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *POPPermissionDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *POPPermissionDto) UnmarshalBinary(b []byte) error {
	var res POPPermissionDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
