// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReleasePermissionsDto release permissions dto
// swagger:model ReleasePermissionsDto
type ReleasePermissionsDto struct {

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// is add to track allowed
	IsAddToTrackAllowed bool `json:"isAddToTrackAllowed,omitempty"`

	// is create allowed
	IsCreateAllowed bool `json:"isCreateAllowed,omitempty"`

	// is delete allowed
	IsDeleteAllowed bool `json:"isDeleteAllowed,omitempty"`

	// is edit allowed
	IsEditAllowed bool `json:"isEditAllowed,omitempty"`

	// is production token edit allowed
	IsProductionTokenEditAllowed bool `json:"isProductionTokenEditAllowed,omitempty"`

	// is remove from track allowed
	IsRemoveFromTrackAllowed bool `json:"isRemoveFromTrackAllowed,omitempty"`
}

// Validate validates this release permissions dto
func (m *ReleasePermissionsDto) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReleasePermissionsDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReleasePermissionsDto) UnmarshalBinary(b []byte) error {
	var res ReleasePermissionsDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
