// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SwitchTenantPageDto switch tenant page dto
// swagger:model SwitchTenantPageDto
type SwitchTenantPageDto struct {

	// allow to leave tenant
	AllowToLeaveTenant bool `json:"allowToLeaveTenant,omitempty"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`
}

// Validate validates this switch tenant page dto
func (m *SwitchTenantPageDto) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SwitchTenantPageDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SwitchTenantPageDto) UnmarshalBinary(b []byte) error {
	var res SwitchTenantPageDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
