// Code generated by go-swagger; DO NOT EDIT.

package endpoint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/e88z4/go_cdd/administration/models"
)

// CreateEndpointUsingPOSTReader is a Reader for the CreateEndpointUsingPOST structure.
type CreateEndpointUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateEndpointUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateEndpointUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewCreateEndpointUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateEndpointUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateEndpointUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateEndpointUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateEndpointUsingPOSTOK creates a CreateEndpointUsingPOSTOK with default headers values
func NewCreateEndpointUsingPOSTOK() *CreateEndpointUsingPOSTOK {
	return &CreateEndpointUsingPOSTOK{}
}

/*CreateEndpointUsingPOSTOK handles this case with default header values.

OK
*/
type CreateEndpointUsingPOSTOK struct {
	Payload *models.EndpointDto
}

func (o *CreateEndpointUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /endpoint-templates/{endpointTemplateId}/endpoints][%d] createEndpointUsingPOSTOK  %+v", 200, o.Payload)
}

func (o *CreateEndpointUsingPOSTOK) GetPayload() *models.EndpointDto {
	return o.Payload
}

func (o *CreateEndpointUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EndpointDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateEndpointUsingPOSTCreated creates a CreateEndpointUsingPOSTCreated with default headers values
func NewCreateEndpointUsingPOSTCreated() *CreateEndpointUsingPOSTCreated {
	return &CreateEndpointUsingPOSTCreated{}
}

/*CreateEndpointUsingPOSTCreated handles this case with default header values.

Created
*/
type CreateEndpointUsingPOSTCreated struct {
}

func (o *CreateEndpointUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /endpoint-templates/{endpointTemplateId}/endpoints][%d] createEndpointUsingPOSTCreated ", 201)
}

func (o *CreateEndpointUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateEndpointUsingPOSTUnauthorized creates a CreateEndpointUsingPOSTUnauthorized with default headers values
func NewCreateEndpointUsingPOSTUnauthorized() *CreateEndpointUsingPOSTUnauthorized {
	return &CreateEndpointUsingPOSTUnauthorized{}
}

/*CreateEndpointUsingPOSTUnauthorized handles this case with default header values.

Unauthorized
*/
type CreateEndpointUsingPOSTUnauthorized struct {
}

func (o *CreateEndpointUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /endpoint-templates/{endpointTemplateId}/endpoints][%d] createEndpointUsingPOSTUnauthorized ", 401)
}

func (o *CreateEndpointUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateEndpointUsingPOSTForbidden creates a CreateEndpointUsingPOSTForbidden with default headers values
func NewCreateEndpointUsingPOSTForbidden() *CreateEndpointUsingPOSTForbidden {
	return &CreateEndpointUsingPOSTForbidden{}
}

/*CreateEndpointUsingPOSTForbidden handles this case with default header values.

Forbidden
*/
type CreateEndpointUsingPOSTForbidden struct {
}

func (o *CreateEndpointUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /endpoint-templates/{endpointTemplateId}/endpoints][%d] createEndpointUsingPOSTForbidden ", 403)
}

func (o *CreateEndpointUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateEndpointUsingPOSTNotFound creates a CreateEndpointUsingPOSTNotFound with default headers values
func NewCreateEndpointUsingPOSTNotFound() *CreateEndpointUsingPOSTNotFound {
	return &CreateEndpointUsingPOSTNotFound{}
}

/*CreateEndpointUsingPOSTNotFound handles this case with default header values.

Not Found
*/
type CreateEndpointUsingPOSTNotFound struct {
}

func (o *CreateEndpointUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /endpoint-templates/{endpointTemplateId}/endpoints][%d] createEndpointUsingPOSTNotFound ", 404)
}

func (o *CreateEndpointUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
