// Code generated by go-swagger; DO NOT EDIT.

package endpoint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/e88z4/go_cdd/administration/models"
)

// UpdateEndpointUsingPUTReader is a Reader for the UpdateEndpointUsingPUT structure.
type UpdateEndpointUsingPUTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateEndpointUsingPUTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateEndpointUsingPUTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewUpdateEndpointUsingPUTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewUpdateEndpointUsingPUTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateEndpointUsingPUTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateEndpointUsingPUTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateEndpointUsingPUTOK creates a UpdateEndpointUsingPUTOK with default headers values
func NewUpdateEndpointUsingPUTOK() *UpdateEndpointUsingPUTOK {
	return &UpdateEndpointUsingPUTOK{}
}

/*UpdateEndpointUsingPUTOK handles this case with default header values.

OK
*/
type UpdateEndpointUsingPUTOK struct {
	Payload *models.EndpointDto
}

func (o *UpdateEndpointUsingPUTOK) Error() string {
	return fmt.Sprintf("[PUT /endpoints/{endpointId}][%d] updateEndpointUsingPUTOK  %+v", 200, o.Payload)
}

func (o *UpdateEndpointUsingPUTOK) GetPayload() *models.EndpointDto {
	return o.Payload
}

func (o *UpdateEndpointUsingPUTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EndpointDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateEndpointUsingPUTCreated creates a UpdateEndpointUsingPUTCreated with default headers values
func NewUpdateEndpointUsingPUTCreated() *UpdateEndpointUsingPUTCreated {
	return &UpdateEndpointUsingPUTCreated{}
}

/*UpdateEndpointUsingPUTCreated handles this case with default header values.

Created
*/
type UpdateEndpointUsingPUTCreated struct {
}

func (o *UpdateEndpointUsingPUTCreated) Error() string {
	return fmt.Sprintf("[PUT /endpoints/{endpointId}][%d] updateEndpointUsingPUTCreated ", 201)
}

func (o *UpdateEndpointUsingPUTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateEndpointUsingPUTUnauthorized creates a UpdateEndpointUsingPUTUnauthorized with default headers values
func NewUpdateEndpointUsingPUTUnauthorized() *UpdateEndpointUsingPUTUnauthorized {
	return &UpdateEndpointUsingPUTUnauthorized{}
}

/*UpdateEndpointUsingPUTUnauthorized handles this case with default header values.

Unauthorized
*/
type UpdateEndpointUsingPUTUnauthorized struct {
}

func (o *UpdateEndpointUsingPUTUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /endpoints/{endpointId}][%d] updateEndpointUsingPUTUnauthorized ", 401)
}

func (o *UpdateEndpointUsingPUTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateEndpointUsingPUTForbidden creates a UpdateEndpointUsingPUTForbidden with default headers values
func NewUpdateEndpointUsingPUTForbidden() *UpdateEndpointUsingPUTForbidden {
	return &UpdateEndpointUsingPUTForbidden{}
}

/*UpdateEndpointUsingPUTForbidden handles this case with default header values.

Forbidden
*/
type UpdateEndpointUsingPUTForbidden struct {
}

func (o *UpdateEndpointUsingPUTForbidden) Error() string {
	return fmt.Sprintf("[PUT /endpoints/{endpointId}][%d] updateEndpointUsingPUTForbidden ", 403)
}

func (o *UpdateEndpointUsingPUTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateEndpointUsingPUTNotFound creates a UpdateEndpointUsingPUTNotFound with default headers values
func NewUpdateEndpointUsingPUTNotFound() *UpdateEndpointUsingPUTNotFound {
	return &UpdateEndpointUsingPUTNotFound{}
}

/*UpdateEndpointUsingPUTNotFound handles this case with default header values.

Not Found
*/
type UpdateEndpointUsingPUTNotFound struct {
}

func (o *UpdateEndpointUsingPUTNotFound) Error() string {
	return fmt.Sprintf("[PUT /endpoints/{endpointId}][%d] updateEndpointUsingPUTNotFound ", 404)
}

func (o *UpdateEndpointUsingPUTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
