// Code generated by go-swagger; DO NOT EDIT.

package registered_plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/e88z4/go_cdd/administration/models"
)

// GetAutoRegisterPluginsUsingGETReader is a Reader for the GetAutoRegisterPluginsUsingGET structure.
type GetAutoRegisterPluginsUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAutoRegisterPluginsUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAutoRegisterPluginsUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAutoRegisterPluginsUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAutoRegisterPluginsUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAutoRegisterPluginsUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAutoRegisterPluginsUsingGETOK creates a GetAutoRegisterPluginsUsingGETOK with default headers values
func NewGetAutoRegisterPluginsUsingGETOK() *GetAutoRegisterPluginsUsingGETOK {
	return &GetAutoRegisterPluginsUsingGETOK{}
}

/*GetAutoRegisterPluginsUsingGETOK handles this case with default header values.

OK
*/
type GetAutoRegisterPluginsUsingGETOK struct {
	Payload *models.ListHolderDto
}

func (o *GetAutoRegisterPluginsUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /registered-plugins][%d] getAutoRegisterPluginsUsingGETOK  %+v", 200, o.Payload)
}

func (o *GetAutoRegisterPluginsUsingGETOK) GetPayload() *models.ListHolderDto {
	return o.Payload
}

func (o *GetAutoRegisterPluginsUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListHolderDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAutoRegisterPluginsUsingGETUnauthorized creates a GetAutoRegisterPluginsUsingGETUnauthorized with default headers values
func NewGetAutoRegisterPluginsUsingGETUnauthorized() *GetAutoRegisterPluginsUsingGETUnauthorized {
	return &GetAutoRegisterPluginsUsingGETUnauthorized{}
}

/*GetAutoRegisterPluginsUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type GetAutoRegisterPluginsUsingGETUnauthorized struct {
}

func (o *GetAutoRegisterPluginsUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /registered-plugins][%d] getAutoRegisterPluginsUsingGETUnauthorized ", 401)
}

func (o *GetAutoRegisterPluginsUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAutoRegisterPluginsUsingGETForbidden creates a GetAutoRegisterPluginsUsingGETForbidden with default headers values
func NewGetAutoRegisterPluginsUsingGETForbidden() *GetAutoRegisterPluginsUsingGETForbidden {
	return &GetAutoRegisterPluginsUsingGETForbidden{}
}

/*GetAutoRegisterPluginsUsingGETForbidden handles this case with default header values.

Forbidden
*/
type GetAutoRegisterPluginsUsingGETForbidden struct {
}

func (o *GetAutoRegisterPluginsUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /registered-plugins][%d] getAutoRegisterPluginsUsingGETForbidden ", 403)
}

func (o *GetAutoRegisterPluginsUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAutoRegisterPluginsUsingGETNotFound creates a GetAutoRegisterPluginsUsingGETNotFound with default headers values
func NewGetAutoRegisterPluginsUsingGETNotFound() *GetAutoRegisterPluginsUsingGETNotFound {
	return &GetAutoRegisterPluginsUsingGETNotFound{}
}

/*GetAutoRegisterPluginsUsingGETNotFound handles this case with default header values.

Not Found
*/
type GetAutoRegisterPluginsUsingGETNotFound struct {
}

func (o *GetAutoRegisterPluginsUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /registered-plugins][%d] getAutoRegisterPluginsUsingGETNotFound ", 404)
}

func (o *GetAutoRegisterPluginsUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
