// Code generated by go-swagger; DO NOT EDIT.

package api_access_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/e88z4/go_cdd/administration/models"
)

// CreateAPIAccessTokenUsingPOSTReader is a Reader for the CreateAPIAccessTokenUsingPOST structure.
type CreateAPIAccessTokenUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAPIAccessTokenUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateAPIAccessTokenUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewCreateAPIAccessTokenUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateAPIAccessTokenUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateAPIAccessTokenUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateAPIAccessTokenUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateAPIAccessTokenUsingPOSTOK creates a CreateAPIAccessTokenUsingPOSTOK with default headers values
func NewCreateAPIAccessTokenUsingPOSTOK() *CreateAPIAccessTokenUsingPOSTOK {
	return &CreateAPIAccessTokenUsingPOSTOK{}
}

/*CreateAPIAccessTokenUsingPOSTOK handles this case with default header values.

OK
*/
type CreateAPIAccessTokenUsingPOSTOK struct {
	Payload *models.APIAccessTokenDto
}

func (o *CreateAPIAccessTokenUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /api-access-tokens][%d] createApiAccessTokenUsingPOSTOK  %+v", 200, o.Payload)
}

func (o *CreateAPIAccessTokenUsingPOSTOK) GetPayload() *models.APIAccessTokenDto {
	return o.Payload
}

func (o *CreateAPIAccessTokenUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIAccessTokenDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAPIAccessTokenUsingPOSTCreated creates a CreateAPIAccessTokenUsingPOSTCreated with default headers values
func NewCreateAPIAccessTokenUsingPOSTCreated() *CreateAPIAccessTokenUsingPOSTCreated {
	return &CreateAPIAccessTokenUsingPOSTCreated{}
}

/*CreateAPIAccessTokenUsingPOSTCreated handles this case with default header values.

Created
*/
type CreateAPIAccessTokenUsingPOSTCreated struct {
}

func (o *CreateAPIAccessTokenUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /api-access-tokens][%d] createApiAccessTokenUsingPOSTCreated ", 201)
}

func (o *CreateAPIAccessTokenUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateAPIAccessTokenUsingPOSTUnauthorized creates a CreateAPIAccessTokenUsingPOSTUnauthorized with default headers values
func NewCreateAPIAccessTokenUsingPOSTUnauthorized() *CreateAPIAccessTokenUsingPOSTUnauthorized {
	return &CreateAPIAccessTokenUsingPOSTUnauthorized{}
}

/*CreateAPIAccessTokenUsingPOSTUnauthorized handles this case with default header values.

Unauthorized
*/
type CreateAPIAccessTokenUsingPOSTUnauthorized struct {
}

func (o *CreateAPIAccessTokenUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api-access-tokens][%d] createApiAccessTokenUsingPOSTUnauthorized ", 401)
}

func (o *CreateAPIAccessTokenUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateAPIAccessTokenUsingPOSTForbidden creates a CreateAPIAccessTokenUsingPOSTForbidden with default headers values
func NewCreateAPIAccessTokenUsingPOSTForbidden() *CreateAPIAccessTokenUsingPOSTForbidden {
	return &CreateAPIAccessTokenUsingPOSTForbidden{}
}

/*CreateAPIAccessTokenUsingPOSTForbidden handles this case with default header values.

Forbidden
*/
type CreateAPIAccessTokenUsingPOSTForbidden struct {
}

func (o *CreateAPIAccessTokenUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /api-access-tokens][%d] createApiAccessTokenUsingPOSTForbidden ", 403)
}

func (o *CreateAPIAccessTokenUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateAPIAccessTokenUsingPOSTNotFound creates a CreateAPIAccessTokenUsingPOSTNotFound with default headers values
func NewCreateAPIAccessTokenUsingPOSTNotFound() *CreateAPIAccessTokenUsingPOSTNotFound {
	return &CreateAPIAccessTokenUsingPOSTNotFound{}
}

/*CreateAPIAccessTokenUsingPOSTNotFound handles this case with default header values.

Not Found
*/
type CreateAPIAccessTokenUsingPOSTNotFound struct {
}

func (o *CreateAPIAccessTokenUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /api-access-tokens][%d] createApiAccessTokenUsingPOSTNotFound ", 404)
}

func (o *CreateAPIAccessTokenUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
